added optimal path to stuck point, and added SPL benchmarking publish…
Yamada-Yoshifumi/snake-robot pull request #6
Opened 2023-03-13 11:39 UTC by Yamada-Yoshifumi

…ed to /spl_value

2023-03-13 13:58 UTC, jl-wang6 commented
looks good

2023-03-15 22:40 UTC, kaicao233 commented
LGTM

2023-03-17 11:51 UTC, kaicao233 requested changes

2023-03-17 11:51 UTC, kaicao233 commented on snake_robot/trajectory_recording.py
> +                optimal_length += np.linalg.norm(shrunk_adjusted_optimal_path[i] - shrunk_adjusted_optimal_path[i+1])
Should here be ```np.array(shrunk_adjusted_optimal_path[i])``` and ```np.array(shrunk_adjusted_optimal_path[i+1])```?

2023-03-17 11:51 UTC, kaicao233 commented on snake_robot/trajectory_recording.py
> +                actual_length += np.linalg.norm(self.path_points[i] - self.path_points[i+1])
Same here

2023-03-17 12:51 UTC, Yamada-Yoshifumi commented on snake_robot/trajectory_recording.py
> +                optimal_length += np.linalg.norm(shrunk_adjusted_optimal_path[i] - shrunk_adjusted_optimal_path[i+1])
Updated, thanks

2023-03-17 12:51 UTC, merged